services:
  postgres:
    image: postgres:14-alpine
    container_name: jobguard-postgres
    environment:
      POSTGRES_DB: jobguard_demo
      POSTGRES_USER: demo
      POSTGRES_PASSWORD: demo123
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../schema/001_initial.sql:/docker-entrypoint-initdb.d/001_initial.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U demo -d jobguard_demo"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: jobguard-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  postgres_data:
